- name: Stop openmrs
  service:
    name=openmrs
    state=stopped
  when: passive is not defined or passive != 'yes'

- name: Download Properties file for Program Auto Enrolment
  get_url:
    url={{ program_auto_enrolment_properties_url }}
    force=yes
    dest=/opt/openmrs/program-auto-enrolment.properties
    owner={{ bahmni_user }}
    group={{ bahmni_group }}
    mode=755

- name: Download omod file for Program Auto Enrolment
  get_url:
    url={{ program_auto_enrolment_omod_url }}
    force=yes
    dest=/opt/openmrs/modules/
    owner={{ bahmni_user }}
    group={{ bahmni_group }}
    mode=755

- name: Start openmrs
  service:
    name=openmrs
    state=started
  when: passive is not defined or passive != 'yes'